// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMK0WKuwvG0rf3g5tHaUfwSt5-UjDLOSk',
    appId: '1:1055006001372:ios:e8da67ef8b73e06471cc19',
    messagingSenderId: '1055006001372',
    projectId: 'agop-finalyear',
    storageBucket: 'agop-finalyear.firebasestorage.app',
    iosBundleId: 'com.example.agopFinalyear',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9P2UInZAopAaA_fIN3LNWT9WfxnSd17s',
    appId: '1:1055006001372:web:5f9a7321d39d83bd71cc19',
    messagingSenderId: '1055006001372',
    projectId: 'agop-finalyear',
    authDomain: 'agop-finalyear.firebaseapp.com',
    storageBucket: 'agop-finalyear.firebasestorage.app',
    measurementId: 'G-80BZM1FCTR',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9P2UInZAopAaA_fIN3LNWT9WfxnSd17s',
    appId: '1:1055006001372:web:5f9a7321d39d83bd71cc19',
    messagingSenderId: '1055006001372',
    projectId: 'agop-finalyear',
    authDomain: 'agop-finalyear.firebaseapp.com',
    storageBucket: 'agop-finalyear.firebasestorage.app',
    measurementId: 'G-80BZM1FCTR',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMK0WKuwvG0rf3g5tHaUfwSt5-UjDLOSk',
    appId: '1:1055006001372:ios:e8da67ef8b73e06471cc19',
    messagingSenderId: '1055006001372',
    projectId: 'agop-finalyear',
    storageBucket: 'agop-finalyear.firebasestorage.app',
    iosBundleId: 'com.example.agopFinalyear',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuY0n9YOF-U8ph6uvgHeKD9zXLbYSNloE',
    appId: '1:1055006001372:android:fcb59f4b7a72e77e71cc19',
    messagingSenderId: '1055006001372',
    projectId: 'agop-finalyear',
    storageBucket: 'agop-finalyear.firebasestorage.app',
  );
}
